<?php
/**
 *
 * This code is part of the article "Using A Config To Write Reusable Code"
 * as published on https://www.alainschlesser.com/.
 *
 * @see       https://www.alainschlesser.com/config-files-for-reusable-code/
 *
 * @package   WPBS\WPBetterSettings
 * @author    Alain Schlesser <alain.schlesser@gmail.com>
 * @license   GPL-2.0+
 * @link      https://www.alainschlesser.com/
 * @copyright 2016 Alain Schlesser
 */

namespace WPBS\WPBetterSettings;

/* @var \ArrayObject $context Context passed through from Settings class. */

?>
<input type='text' name='wpbs_option_2[wpbs_last_name]'
       value='<?php echo esc_html( $context->value ); ?>'>
