<?php
/**
 *
 * This code is part of the article "Using A Config To Write Reusable Code"
 * as published on https://www.alainschlesser.com/.
 *
 * @see       https://www.alainschlesser.com/config-files-for-reusable-code/
 *
 * @package   WPBS\WPBetterSettings
 * @author    Alain Schlesser <alain.schlesser@gmail.com>
 * @license   GPL-2.0+
 * @link      https://www.alainschlesser.com/
 * @copyright 2016 Alain Schlesser
 */

namespace WPBS\WPBetterSettings;

esc_html_e(
	'These settings store a completely useless pair of first and last names.',
	'as-settings-better-v1'
);
