<?php
/**
 * WP Better Settings
 *
 * A simplified OOP implementation of the WP Settings API.
 *
 * @package   WPBS\WP_Better_Settings
 * @author    Typist Tech <wp-better-settings@typist.tech>
 * @license   GPL-2.0+
 * @link      https://www.typist.tech/
 * @copyright 2017 Typist Tech
 */

namespace WPBS\WPBetterSettings\partials;

/* @var \ArrayObject $context Context passed through from Settings class. */

$type = $type ?? 'text';

$name = sprintf(
	'%s[%s]',
	esc_html( $context->option_name ),
	esc_html( $context->id )
);

$desc_id = $context->id . '-description';

echo '<input class="regular-text" ';
echo 'name="' . esc_attr( $name ) . '" ';
echo 'type="' . esc_attr( $type ) . '" ';
echo 'id="' . esc_attr( $context->id ) . '" ';
echo 'value="' . esc_attr( $context->value ) . '" ';
if ( ! empty( $context->desc ) ) {
	echo 'aria-describedby="' . esc_attr( $desc_id ) . '" ';
}
disabled( $context->disabled );
echo ' >';

if ( ! empty( $context->desc ) ) {
	echo '<p class="description" ';
	echo 'id="' . esc_attr( $desc_id ) . '">';
	echo wp_kses_post( $context->desc );
	echo '</p>';
}
