<?php
/**
 * WP Better Settings
 *
 * A simplified OOP implementation of the WP Settings API.
 *
 * @package   WPBS\WP_Better_Settings
 * @author    Typist Tech <wp-better-settings@typist.tech>
 * @license   GPL-2.0+
 * @link      https://www.typist.tech/
 * @copyright 2017 Typist Tech
 */

namespace WPBS\WPBetterSettings\partials;

/* @var \ArrayObject $context Context passed through from Settings class. */

$name    = sprintf(
	'%s[%s]',
	esc_html( $context->option_name ),
	esc_html( $context->id )
);
$desc_id = $context->id . '-description';

echo '<textarea ';
echo 'name="' . esc_attr( $name ) . '" ';
echo 'id="' . esc_attr( $context->id ) . '" ';
echo 'class="regular-text" ';
if ( absint( $context->rows ) > 0 ) {
	echo 'rows="' . absint( $context->rows ) . '" ';
}
if ( ! empty( $context->desc ) ) {
	echo 'aria-describedby="' . esc_attr( $desc_id ) . '" ';
}
disabled( $context->disabled );
echo '>';

echo esc_textarea( $context->value );

echo '</textarea>';

if ( ! empty( $context->desc ) ) {
	echo '<p class="description" ';
	echo 'id="' . esc_attr( $desc_id ) . '">';
	echo wp_kses_post( $context->desc );
	echo '</p>';
}
